# Generated by Django 5.2.8 on 2025-11-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resource', models.CharField(choices=[('Auditorium', 'Auditorium'), ('Conference Hall', 'Conference Hall'), ('Multimedia Room', 'Multimedia Room'), ('Basketball Court', 'Basketball Court'), ('Football Court', 'Football Court'), ('Volleyball Court', 'Volleyball Court'), ('Badminton Hall', 'Badminton Hall')], max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
